version: '2.1'

services:
  memcached:
    image: 'bitnami/memcached:latest'

  backend:
    image: "flickrphotosearch-backend:v1"
    ports:
     - "8101:8080"
    env_file:
      - backend/.env

  frontend:
    image: "flickrphotosearch-frontend:v1.1"
    ports:
     - "8100:80"
    env_file:
      - frontend/.env
