version: '2.1'

services:
  memcached:
    image: 'bitnami/memcached:latest'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BUILD_DIR=./build
        - BINARY_NAME=github.com/ktamashun/flickrphotosearch/backend-docker
    ports:
     - "18000:18000"
    env_file:
      - backend/.env

  video-search:
    build:
      context: ./video-search
      dockerfile: Dockerfile
      args:
        - BUILD_DIR=./build
        - BINARY_NAME=github.com/ktamashun/flickrphotosearch/video-search-docker
    ports:
     - "18001:18000"
    env_file:
      - video-search/.env

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      args:
        - BUILD_DIR=./build
        - BINARY_NAME=github.com/ktamashun/flickrphotosearch/api-gateway-docker
    links:
      - backend
    ports:
     - "18080:18080"
    env_file:
      - api-gateway/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILD_DIR=./build
        - BINARY_NAME=github.com/ktamashun/flickrphotosearch/frontend-docker
    ports:
     - "10080:80"
    env_file:
      - frontend/.env
