version: '2.1'

services:
  memcached:
    image: 'bitnami/memcached:latest'

  backend:
    image: "flickrphotosearch-backend:v1"
    ports:
     - "18000:18000"
    env_file:
      - backend/.env

  backend:
    image: "flickrphotosearch-api-gateway:v1"
    ports:
     - "18080:18080"
    env_file:
      - api-gateway/.env

  frontend:
    image: "flickrphotosearch-frontend:v1.1"
    ports:
     - "10080:80"
    env_file:
      - frontend/.env
